services:
  envoy:
    image: envoyproxy/envoy:v1.25-latest
    ports:
      - "8080:80"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  mysql:
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portal
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build:
      dockerfile: backend.dockerfile
      target: production
      context: .
    env_file:
      - ./dev.env
    ports:
      - "80:80"
    volumes:
      - gopkg:/go/pkg
      - ./backend:/backend
      - ./backend/schema:/schema
      - ./seeds:/seeds

  frontend:
    build:
      dockerfile: frontend.dockerfile
      target: production
      context: .
    env_file:
      - ./dev.env
    ports:
      - "3000:3000"
    volumes:
      - pnpm-store:/frontend/.pnpm-store
      - node_modules:/frontend/node_modules
      - ./frontend:/frontend

volumes:
  mysql:
  gopkg:
  pnpm-store:
  node_modules:
