name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - backend/**

env:
  TEST_EMAIL_SMTP_SERVER: ${{secrets.TEST_EMAIL_SMTP_SERVER}}
  TEST_EMAIL_TO: ${{secrets.TEST_EMAIL_TO}}
  TEST_EMAIL_PASS: ${{secrets.TEST_EMAIL_PASS}}
  TEST_EMAIL_FROM: ${{secrets.TEST_EMAIL_FROM}}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database

    container:
      image: golang:1.19
      env:
        DATABASE_URL: "root:password@tcp(mysql)/?parseTime=true&multiStatements=true"

    steps:
      - uses: actions/checkout@v3

      - name: Install mysqldef
        run: |
          wget https://github.com/k0kubun/sqldef/releases/download/v0.13.5/mysqldef_linux_amd64.tar.gz
          tar xvf mysqldef_linux_amd64.tar.gz
          chmod +x mysqldef
          mv mysqldef /usr/local/bin

      - name: Coverage
        working-directory: backend
        run: go install && go get github.com/golang/mock/mockgen@v1.6.0 && go test -v -cover -race -tags use_external_db -coverprofile=coverage ./...

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/coverage
          flags: backend
          name: codecov-backend
          fail_ci_if_error: false
          verbose: true
