name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: pnpm-setup
        run: npm install -g pnpm@next-7
      - name: pnpm-install
        run: pnpm i
      - name: Prettier
        run: pnpm run format:check
      - name: ESLint
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck
      - name: Build
        run: pnpm run build
