name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - frontend/**

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Prettier
        run: pnpm run format:check
      - name: ESLint
        run: pnpm run lint
      - name: Typecheck
        run: pnpm run typecheck
      - name: Build
        run: pnpm run build
